version: '3'
services:
  api:
    # environment: # for a full list check the corresponding properties-builder file
    #   - DB_DATABASE: dashboarddb
    #   - DB_HOST: db
    #   - DB_PORT: 27017
    #   - DB_USERNAME: dashboarduser
    #   - DB_PASSWORD: dbpassword
    # volumes:
    #   - ./logs:/hygieia/logs

  api-audit:
    # environment:

  ui:
    # environment:

  appdynamics-collector:
    # environment:

  artifactory-artifact-collector:
    # environment:

  bamboo-build-collector:
    # environment:

  bitbucket-collector:
    # environment:

  chat-ops-collector:
    # environment:

  github-collector:
    environment:
  - GITHUB_HOST=github.com
  - GITHUB_CRON=0 * * * * *
  - GITHUB_COMMIT_THRESHOLD_DAYS=300

  hpsm-cmdb-collector:
    # environment:

  github-graphql-collector:
    # environment:

  gitlab-feature-collector:
    # environment:

  gitlab-scm-collector:
    # environment:

  jenkins-build-collector:
    environment:
  - JENKINS_CRON=0 * * * * *
  - JENKINS_MASTER=http://192.168.99.100:9100
  - JENKINS_USERNAME=XXXXXXXXXXXXXXXXXXXXXX
  - JENKINS_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXX

  jenkins-codequality-collector:
    # environment:

  jenkins-cucumber-test-collector:
   environment:
  - JENKINS_CRON=0 * * * * *
  - JENKINS_MASTER=http://192.168.99.100:9100
  - JENKINS_USERNAME=XXXXXXXXXXXXXXXXXXXXXX
  - JENKINS_API_KEY=XXXXXXXXXXXXXXXXX
  - JENKINS_CUCUMBER_JSON_FILENAME=cucumber-report.json

  jira-collector:
    environment:
  - JIRA_BASE_URL=https://mycompany.atlassian.net/
  - JIRA_CREDENTIALS=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - JIRA_ISSUE_TYPE_ID=10200
  - JIRA_SPRINT_DATA_FIELD_NAME=customfield_10007
  - JIRA_EPIC_FIELD_NAME=customfield_10008

  nexus-iq-collector:
    # environment:

  sonar-codequality-collector:
    environment:
  - SONAR_URL=http://192.168.99.100:9000
  - SONAR_CRON=0 * * * * *

  subversion-collector:
    # environment:

  udeploy-collector:
    # environment:

  versionone-collector:
    # environment:

  xldeploy-collector:
    # environment:
